[package]
name = "web"
version = "0.1.0"
authors = ["leocavalcante <lc@leocavalcante.com>"]
edition = "2018"

[dependencies]
stdweb = "0.4"
yew = "0.11"
serde = "1.0"
serde_json = "1.0"
failure = "0.1"